### ISSUE TITLE
Tests are broken

### ISSUE THREAD

**Issue by e-kolpakov** [mckinseyacademy/django-upload-validator#3]
```
$ python runtests.py 
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
F..E..EE.....
======================================================================
ERROR: test_valid_types_10_sample_xlsx (django-upload-validator.tests.tests.TestFileValidator)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/john/.virtualenvs/django-upload-validator/local/lib/python2.7/site-packages/ddt.py", line 139, in wrapper
    return func(self, *args, **kwargs)
  File "/work/OpenCraft/mckinsey/django-upload-validator/tests/tests.py", line 45, in test_valid_types
    validator(file_obj)
  File "/work/OpenCraft/mckinsey/django-upload-validator/upload_validator/__init__.py", line 63, in __call__
    code='invalid_type'
ValidationError: [u"File type 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' is not allowed. Allowed types are: 'msword, pdf, vnd.ms-powerpoint, vnd.ms-excel, tiff, jpeg, png'."]

======================================================================
ERROR: test_valid_types_3_sample_docx (django-upload-validator.tests.tests.TestFileValidator)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/john/.virtualenvs/django-upload-validator/local/lib/python2.7/site-packages/ddt.py", line 139, in wrapper
    return func(self, *args, **kwargs)
  File "/work/OpenCraft/mckinsey/django-upload-validator/tests/tests.py", line 45, in test_valid_types
    validator(file_obj)
  File "/work/OpenCraft/mckinsey/django-upload-validator/upload_validator/__init__.py", line 63, in __call__
    code='invalid_type'
ValidationError: [u"File type 'application/vnd.openxmlformats-officedocument.wordprocessingml.document' is not allowed. Allowed types are: 'msword, pdf, vnd.ms-powerpoint, vnd.ms-excel, tiff, jpeg, png'."]

======================================================================
ERROR: test_valid_types_4_sample_pptx (django-upload-validator.tests.tests.TestFileValidator)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/john/.virtualenvs/django-upload-validator/local/lib/python2.7/site-packages/ddt.py", line 139, in wrapper
    return func(self, *args, **kwargs)
  File "/work/OpenCraft/mckinsey/django-upload-validator/tests/tests.py", line 45, in test_valid_types
    validator(file_obj)
  File "/work/OpenCraft/mckinsey/django-upload-validator/upload_validator/__init__.py", line 63, in __call__
    code='invalid_type'
ValidationError: [u"File type 'application/vnd.openxmlformats-officedocument.presentationml.presentation' is not allowed. Allowed types are: 'msword, pdf, vnd.ms-powerpoint, vnd.ms-excel, tiff, jpeg, png'."]

======================================================================
FAIL: test_extension_check (django-upload-validator.tests.tests.TestFileValidator)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/work/OpenCraft/mckinsey/django-upload-validator/tests/tests.py", line 85, in test_extension_check
    self.assertEqual(code, 'invalid_extension')
AssertionError: 'invalid_type' != 'invalid_extension'

----------------------------------------------------------------------
Ran 13 tests in 0.060s

FAILED (failures=1, errors=3)
```

**Comment by naeem91** [comment]
Hi @e-kolpakov thanks for reporting. Broken tests are fixed now by adding the allowed cases for OpenOffice docs types.

The underlying problem is actually the difference between the versions of `libmagic1` OS level library which python-magic uses. 

By default following versions are found by default for Ubuntu:
For Ubuntu 12.04 -> libmagic1=5.09
For Ubuntu 16.04 -> libmagic1=5.25

Different versions of this library report mimes differently. Obviously the latest versions are more specific and accurate in reporting the mimes e.g; libmagic5.25 reports specific mimes for OpenOffice docs instead of reporting them under `application/msword`
